{
 "title": "UrbanOS Pipeline Health",
 "description": "UrbanOS Pipeline Health",
 "time": { "from": "now-30m-30s", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "dataset_id",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset, topic)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Topics Input",
   "type": "graph",
   "description": "Rate of data written to Kafka topics by topic name (including dataset id). Data is presented in a log scale to show low volume datasets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pipeline:topic:throughput{dataset_id=~\".*([[dataset_id]]).*\"}",
     "legendFormat": "{{dataset_title}} - {{stage}}"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{kubernetes_namespace=\"streaming-prime\", topic=~\"(streaming-persisted|streaming-dead-letters)\"}[2m]) > 0) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Rate of Events Handled",
   "type": "graph",
   "description": "Rate of events handled by App and Dataset. Data is presented in a Log scale to show lower frequency events.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pipeline:event_stream:events_handled{dataset_id=~\".*[[dataset_id]].*\"}",
     "legendFormat": "{{dataset_title}} | {{app}} | {{event_type}}"
    }
   ]
  },
  {
   "title": "Current Lag (By Consumer Group)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pipeline:topic:lag{dataset_id=~\".*([[dataset_id]]).*\"}",
     "legendFormat": "{{dataset_title}} | {{app}} | {{stage}}"
    },
    { "expr": "pipeline:event_stream:lag", "legendFormat": "{{app}} - event stream" }
   ]
  },
  {
   "title": "Log Messages per Second per App",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Log Messages per Sec." }
   ],
   "targets": [
    { "expr": "pipeline:log_message_rate", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Apps in Crash Loops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[5m]) > 0) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Dataset Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "dataset_info_gauge{dataset_id=~\".*([[dataset_id]]).*\"}"
    }
   ]
  }
 ]
}